### ISSUE TITLE
text is selected and no moving happen

### ISSUE THREAD

**Issue by iamamitnegi** [isocra/TableDnD#50]
Please help me on below issue:

When I click and move over table row, the text is selected and no moving happens.

**Comment by iamamitnegi** [comment]
Hurry!!! I I have found it's solution myself.

we have to allow HTML tag elements as blow:
if (ev.target.tagName == "TD" || ev.target.tagName == "P" || ev.target.tagName == "LI" || ev.target.tagName == "UL")

**Comment by bkdotcom** [comment]
why is this wrapped in this if statement?
```
if (e.target.tagName == "TD") {
    $.tableDnD.initialiseDrag(this, table, this, e, config);
    return false;
}
```
I ran into an issue when my TD contained <span>s

**Comment by Bibendus83** [comment]
So, why exactly does this check exists?
This blocks the drag event whenever any other html element is contained inside the TD, for example images, spans or divs.
I removed the "if (e.target.tagName == "TD") {" line and it works great, any counter indications?
