### ISSUE TITLE
[BUG] Firefox 35 is crashing

### ISSUE THREAD

**Issue by temuri416** [isocra/TableDnD#55]
http://jsfiddle.net/DenisHo/dxpLrcd9/embedded/result/

In FF 35 on drag start there is JS error:

ReferenceError: event is not defined
	if (event.changedTouches)

Thank you!

**Comment by JacobWDavidson** [comment]
I'm having the same issue. Have you found a work around?

**Comment by piotr-przebieracz** [comment]
I've created a pull request for this error: 
https://github.com/isocra/TableDnD/pull/57

**Comment by brendon** [comment]
Since #57 is merged, this can be closed.

**Comment by isocra** [comment]
Thanks @brendon
