### ISSUE TITLE
Tag Project for Bower

### ISSUE THREAD

**Issue by throrin19** [isocra/TableDnD#61]
Hello, it's possible to tag your project ?

Bower works with version number. In your case, the bower JSON save only an `*` version because you have'nt tagged your project.

The only one solution to update your library is to remove folder and relaunch `bower install` command. Please fix that

**Comment by Miw0** [comment]
+1

**Comment by isocra** [comment]
Done! @throrin19: can you check that it works as expected?

**Comment by mathieumg** [comment]
It works as expected over here. I was wondering, were there any plans to publish the package to npm as well? I could open an issue if you're interested.

**Comment by throrin19** [comment]
the tag works fine, thanks :). Thinks to tag new versions, bower use your tags automatically
