### ISSUE TITLE
Windows 10, Chrome

### ISSUE THREAD

**Issue by svallen** [isocra/TableDnD#67]
Drag/Drop won't work at all in Chrome on Windows 10.  Edge works fine.

Any ideas on how to get this working on Chrome?

**Comment by isocra** [comment]
Do you have anything to go on? It works fine on Chrome for Mac. Have you tried the [JSFiddle](http://jsfiddle.net/DenisHo/dxpLrcd9/embedded/result/) example to check that's working? If it isn't, could you look at the Chrome console to see what errors you're getting?

**Comment by svallen** [comment]
Chrome Mac works fine.

It is Chrome Windows 10 (on Surface Book that I have) that it isn't working.

I had a client who has Windows 8 say it wasn't working either on Chrome.

Console has no errors showing either on my actual page.

Here is quick video: https://www.youtube.com/watch?v=C-JRstcj8kc

I went to the JSFiddle and some errors were thrown [see image] (looks like because of the touchscreen factor of the Surface Book), but my Client just has regular Windows 8 laptop.




![img_2809](https://cloud.githubusercontent.com/assets/6169781/18034106/9ed2caf8-6d02-11e6-9c9c-db53c39e4234.JPG)

**Comment by isocra** [comment]
I wonder if it's a problem with the way TableDnD handles touch. For example it could be that on the Surface we're listening only for touch events and not mouse movement? (It's a while since I looked at that bit of the code.) Did you try using your finger to see if it works?

**Comment by NeoLegends** [comment]
Just tried using my finger on my Surface Pro 4, doesn't work.

**Comment by isocra** [comment]
Hi @NeoLegends and @svallen, I haven't got access to a Surface. Is there any chance you could do some debugging to see if it's calling the `initialiseDrag` method (please try it with both the mouse and finger to see if there's any difference).

Thanks!!

**Comment by NeoLegends** [comment]
I noticed it doesn't work on at least one other Win10 + Touch device (Dell XPS something). I'll see what i can do about the debugging.

**Comment by astax-t** [comment]
I had the same problem in Chrome on Windows 10, but it's gone when I updated tablednd to the latest version as of today.

**Comment by epalm** [comment]
I'm seeing this problem as well, when using my laptop (Dell Latitude E5440) hooked up to my touchscreen monitor (Dell P2314T).  When I unplug the touchscreen monitor, everything works fine.  This is on Windows 7 Pro using jquery.tablednd.js 11-12-2014.  If that isn't the latest tablednd release, I'll try updating and see what happens.

**Comment by isocra** [comment]
Thanks for flagging this up, it's obviously an issue that's specific to touch. I'm afraid I've still not got access to a Windows machine with a touch screen so am not in a position to fix it directly. If anyone has a moment could you find out the following:

1. Does it matter which browser you use? i.e. is it only Chrome on Windows 10, or does it affect Edge as well? Or other browsers?
2. If you have Chrome could you put a JavaScript breakpoint on `initialiseDrag` to see if is being called when you start to drag. Is it different with the mouse and the finger?
3. If you have an Android tablet, could you test it there too? 

Thanks, and sorry you're having problems!

**Comment by fappels** [comment]
I think binding to both touch and mouse events is needed. If I listen to mouse events on a touch device it works.
By the way, the plugin also stopped working on firefox v51 -> v52 update.
What are the minimum jquery version requirements for the 0.9 rc version. I was trying the RC version  on jquery 1.12 but it doesn't seem to work.

**Comment by brendon** [comment]
@fappels, I think it's jQuery 3 compatible now with this fix: https://github.com/isocra/TableDnD/pull/76

**Comment by brendon** [comment]
Closed by https://github.com/isocra/TableDnD/commit/b89aea3ee74d4872f02484dffa85b5dfac7b2aa7
