### ISSUE TITLE
Don't require table.id if serializeParamName present?

### ISSUE THREAD

**Issue by brendon** [isocra/TableDnD#68]
On this line: https://github.com/isocra/TableDnD/blob/master/js/jquery.tablednd.js#L614 we're checking for the existence of the table's `id`. I don't think this should be necessary unless `serializeParamName` isn't set as otherwise the table `id` isn't required.

What do you think?

**Comment by isocra** [comment]
Hi @brendon, yes looks like you're right.

**Comment by brendon** [comment]
Thanks @isocra, do you want a PR on that or is it easy enough to do a quick edit? :)

**Comment by brendon** [comment]
Hope the PR saves you some time :)

**Comment by isocra** [comment]
Just what I needed! Thanks :-)

**Comment by brendon** [comment]
You're welcome :)
