### ISSUE TITLE
Does not work when there are more than one table.

### ISSUE THREAD

**Issue by v-dem** [isocra/TableDnD#71]
The problem is in title. Tables are creating and removing dynamically, of course I initialize tableDnD for each. All is working excellent only when there's only one table. When two or more, I see "Uncaught TypeError: Cannot read property 'length' of undefined" message. This is error trace:
map	@	jquery-2.1.4.min.js:2
currentOrder	@	jquery.tablednd.min.js:264
initialiseDrag	@	jquery.tablednd.min.js:272
(anonymous function)	@	jquery.tablednd.min.js:242
dispatch	@	jquery-2.1.4.min.js:3
r.handle	@	jquery-2.1.4.min.js:3

**Comment by isocra** [comment]
Hi @v-dem,

It does work with more than one table, see this example: http://jsfiddle.net/DenisHo/dxpLrcd9/embedded/result/

Could you check that you're uniquely identifying each table, e.g. referencing it with an ID or using some other way to get at the right one?

**Comment by v-dem** [comment]
Hello, they don't have IDs, I call tableDnD for table created by JS code (and reference it as jQuery object), but obvious this (very good, by the way) plugin does work for more than one table, so there's my own bug somewhere. Thank you :)
