### ISSUE TITLE
Cannot set property 'touchstart' of undefined on Android with modern jQuery

### ISSUE THREAD

**Issue by cubiclesoft** [isocra/TableDnD#73]
Running jQuery 3.1.1 with tableDnD.  Replicated on both a real device and in the Android Studio emulator (both Nougat).  Once I hooked in with Chrome Dev Tools to the emulator, I get (in the unminified file):

`jquery.tablednd.js:95 Uncaught TypeError: Cannot set property 'touchstart' of undefined`

The exception causes tableDnD to fail to load.  The culprit:

````
// If we're on a touch device, then wire up the events
// see http://stackoverflow.com/a/8456194/1316086
hasTouch
    && $.each("touchstart touchmove touchend".split(" "), function(i, name) {
        $.event.fixHooks[name] = $.event.mouseHooks;   // <-- Line 95.
    });
````

The quick solution seems to be, with newer jQuery, to comment out/remove those lines of code.  The plugin starts functioning as expected without any errors.  A better solution could be to put a try-catch around the line causing the problem so older jQuery continues to work and the exception is then caught and ignored under newer jQuery.  This seems to work okay:

````
// If we're on a touch device, then wire up the events
// see http://stackoverflow.com/a/8456194/1316086
hasTouch
    && $.each("touchstart touchmove touchend".split(" "), function(i, name) {
        try { $.event.fixHooks[name] = $.event.mouseHooks; } catch(e) { }
    });
````

**Comment by brendon** [comment]
Perhaps submitting a Pull Request would help speed things along? :) I'm not sure if @isocra is still watching this project but I did manage to get him to merge a PR of mine late last year.

**Comment by brendon** [comment]
The problem is that `fixHooks` was removed. I've opened a ticket here as they want to know how it's being used in the wild. Hopefully they'll have some advice on how to properly do this now:

https://github.com/jquery/jquery/issues/3748

**Comment by brendon** [comment]
Hi @cubiclesoft, I've done a test with just removing that hack entirely with jQuery 3. The DnD works fine on an iPad (emulator) and also in-browser.

@isocra, do you recall what this was added for? I suspect perhaps it has a hack to grab `pageX` and `pageY` from `event` but since that time (according to git blame) you've added:

```
if (e.originalEvent.changedTouches)
            return {
                x: e.originalEvent.changedTouches[0].clientX,
                y: e.originalEvent.changedTouches[0].clientY
            };
```

and that properly deals with getting the x and y coordinates of the touch.

I'll do up a PR that just removes this hack. Would you mind merging that for me?

**Comment by isocra** [comment]
Hi folks,

Sorry, as I'm not using TableDnD at the moment, I don't get much (any) time to fix issues any more. This code was added by a contributor a couple of years ago, in an effort to get touch working better. Looks like it wasn't a good approach.

**Comment by cubiclesoft** [comment]
@brendon @isocra - Thanks for following up on this.

**Comment by brendon** [comment]
Thanks @isocra :) I understand. If you'd like to make me a maintainer on this project I don't mind. I also maintain the `acts_as_list` rails gem if that helps for credibility.

Yes, it certainly seemed like a bit of a hack :)
