### ISSUE TITLE
Register package on NPM an/or Yarn

### ISSUE THREAD

**Issue by Sander-Toonen** [isocra/TableDnD#82]
Bower probably won't be around for long anymore. Even the Bower team is recommending developers to move over to Yarn. Would it therefore be possible to register this package on NPM or Yarn? 

See:
https://docs.npmjs.com/getting-started/publishing-npm-packages
https://yarnpkg.com/lang/en/docs/publishing-a-package/

**Comment by isocra** [comment]
Yes I've been thinking the same thing. We'll do it very soon.

**Comment by isocra** [comment]
@Sander-Toonen just to let you know we've registered with npm (https://www.npmjs.com/package/tablednd). At the moment, this is bound up with making a new release (see https://github.com/isocra/TableDnD/pull/80)

So I'm closing this issue. Full npm integration should be available in a few days. We'll look at yarn shortly afterwards (but as I understand it, yarn works with npm packages anyway).

**Comment by brendon** [comment]
Hi @isocra, it looks like `main:` in the `package.json` file might not be pointing at the right place. I had to do: `import "tablednd/dist/jquery.tablednd.js";` instead of `import "tablednd";`.

**Comment by isocra** [comment]
Ah yes, looks like you're right
