### ISSUE TITLE
Continuos Integration Tool

### ISSUE THREAD

**Issue by guilhermeddf** [isocra/TableDnD#95]
Does this project use any Continuous Integration Tool? If so, is it online? (TravisCI, CircleCI), or offline tool (Jenkins, Hudson).

**Comment by isocra** [comment]
Hi @guilhermeddf, no there's no need for a CI tool at the moment. I use [release-it](https://github.com/release-it/release-it) to create new versions but that's it. Ideally we'd add some regression testing and better release management, but I haven't got the time at the moment.

**Comment by guilhermeddf** [comment]
Thank you!
